// Code generated by goyacc -p grits -o parser/parser.y.go parser/parser.y. DO NOT EDIT.

// Run this after each change:
// goyacc -p grits -o parser/parser.y.go parser/parser.y
//
//line parser/parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser/parser.y:4

import (
	"grits/position"
	"grits/process"
	"grits/types"
	"io"
	"strconv"
)

//line parser/parser.y:16
type gritsSymType struct {
	yys                   int
	strval                string
	currPosition          position.Position
	common_type           unexpandedProcessOrFunction
	statements            []unexpandedProcessOrFunction
	name                  process.Name
	names                 []process.Name
	form                  process.Form
	branches              []*process.BranchForm
	sessionType           types.SessionType
	sessionTypeInitial    types.SessionTypeInitial
	sessionTypeAltInitial []types.OptionInitial
	polarity              types.Polarity
	faultTolerancePromise uint64
}

const LABEL = 57346
const LEFT_ARROW = 57347
const RIGHT_ARROW = 57348
const UP_ARROW = 57349
const DOWN_ARROW = 57350
const EQUALS = 57351
const DOT = 57352
const SEQUENCE = 57353
const COLON = 57354
const COMMA = 57355
const LPAREN = 57356
const RPAREN = 57357
const LSBRACK = 57358
const RSBRACK = 57359
const LANGLE = 57360
const RANGLE = 57361
const PIPE = 57362
const SEND = 57363
const RECEIVE = 57364
const CASE = 57365
const CLOSE = 57366
const WAIT = 57367
const CAST = 57368
const SHIFT = 57369
const ACCEPT = 57370
const ACQUIRE = 57371
const DETACH = 57372
const RELEASE = 57373
const DROP = 57374
const SPLIT = 57375
const PUSH = 57376
const NEW = 57377
const SNEW = 57378
const TYPE = 57379
const LET = 57380
const IN = 57381
const END = 57382
const SPRC = 57383
const PRC = 57384
const FORWARD = 57385
const SELF = 57386
const PRINT = 57387
const PLUS = 57388
const MINUS = 57389
const TIMES = 57390
const AMPERSAND = 57391
const UNIT = 57392
const LCBRACK = 57393
const RCBRACK = 57394
const LOLLI = 57395
const PERCENTAGE = 57396
const ASSUMING = 57397
const EXEC = 57398
const SPAWN = 57399
const SYNC = 57400
const AT = 57401

var gritsToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LABEL",
	"LEFT_ARROW",
	"RIGHT_ARROW",
	"UP_ARROW",
	"DOWN_ARROW",
	"EQUALS",
	"DOT",
	"SEQUENCE",
	"COLON",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"LSBRACK",
	"RSBRACK",
	"LANGLE",
	"RANGLE",
	"PIPE",
	"SEND",
	"RECEIVE",
	"CASE",
	"CLOSE",
	"WAIT",
	"CAST",
	"SHIFT",
	"ACCEPT",
	"ACQUIRE",
	"DETACH",
	"RELEASE",
	"DROP",
	"SPLIT",
	"PUSH",
	"NEW",
	"SNEW",
	"TYPE",
	"LET",
	"IN",
	"END",
	"SPRC",
	"PRC",
	"FORWARD",
	"SELF",
	"PRINT",
	"PLUS",
	"MINUS",
	"TIMES",
	"AMPERSAND",
	"UNIT",
	"LCBRACK",
	"RCBRACK",
	"LOLLI",
	"PERCENTAGE",
	"ASSUMING",
	"EXEC",
	"SPAWN",
	"SYNC",
	"AT",
}

var gritsStatenames = [...]string{}

const gritsEofCode = 1
const gritsErrCode = 2
const gritsInitialStackSize = 16

//line parser/parser.y:279

// Parse is the entry point to the parser.
func Parse(r io.Reader) (allEnvironment, error) {
	l := newLexer(r)
	gritsParse(l)
	allEnvironment := allEnvironment{}
	select {
	case err := <-l.Errors:
		return allEnvironment, err
	default:
		// allEnvironment := l
		allEnvironment.procsAndFuns = l.processesOrFunctionsRes
		return allEnvironment, nil
	}
}

//line yacctab:1
var gritsExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 72,
	4, 76,
	7, 76,
	8, 76,
	14, 76,
	46, 76,
	49, 76,
	50, 76,
	-2, 65,
}

const gritsPrivate = 57344

const gritsLast = 292

var gritsAct = [...]uint8{
	3, 142, 69, 70, 153, 85, 107, 101, 119, 58,
	36, 170, 64, 57, 204, 34, 45, 67, 145, 168,
	109, 108, 53, 32, 187, 26, 25, 7, 129, 211,
	24, 186, 102, 31, 33, 179, 37, 103, 40, 41,
	42, 43, 44, 27, 28, 71, 188, 180, 66, 102,
	130, 102, 133, 161, 103, 158, 103, 134, 181, 147,
	127, 185, 52, 22, 35, 29, 30, 78, 135, 79,
	97, 95, 81, 61, 72, 104, 208, 105, 106, 176,
	110, 113, 86, 115, 76, 116, 117, 54, 151, 93,
	94, 87, 122, 88, 124, 98, 71, 120, 71, 125,
	111, 83, 92, 131, 123, 72, 137, 138, 38, 114,
	39, 144, 139, 141, 136, 76, 74, 4, 146, 75,
	73, 154, 155, 128, 150, 86, 68, 155, 152, 173,
	159, 160, 174, 162, 126, 47, 48, 49, 50, 51,
	86, 148, 118, 166, 149, 167, 86, 74, 112, 171,
	75, 73, 172, 90, 156, 62, 71, 177, 169, 91,
	214, 71, 213, 164, 178, 120, 175, 210, 209, 184,
	183, 182, 132, 189, 191, 84, 82, 192, 80, 217,
	206, 71, 194, 197, 198, 199, 193, 190, 202, 203,
	89, 205, 105, 106, 207, 220, 201, 165, 157, 96,
	143, 59, 212, 163, 140, 65, 215, 216, 195, 196,
	218, 219, 9, 200, 221, 222, 121, 100, 223, 63,
	60, 224, 15, 56, 55, 46, 6, 2, 1, 5,
	23, 8, 10, 12, 13, 99, 77, 21, 20, 19,
	14, 18, 17, 0, 0, 26, 25, 0, 9, 0,
	24, 11, 22, 16, 29, 30, 0, 0, 15, 0,
	0, 0, 6, 27, 28, 5, 0, 8, 10, 12,
	13, 0, 0, 0, 0, 0, 14, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 11, 22, 16,
	29, 30,
}

var gritsPact = [...]int16{
	208, -1000, -1000, -1000, -1000, 19, 19, 5, 19, 96,
	19, 19, 19, 19, 19, 244, 221, -12, -12, -12,
	-12, -12, -1000, 18, 71, 220, 219, 197, 216, -1000,
	-1000, 55, -1000, 142, 215, 201, -10, 112, 101, 19,
	-1000, 19, 167, 54, 165, 86, 164, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 19, 77, 181, -1000, 140, 147,
	88, 19, 19, 53, 194, -1000, 52, 19, 213, -52,
	-16, 70, -1000, -1000, -30, -31, 101, 85, 135, -1000,
	244, 19, 244, -1000, 244, 69, 129, 197, 212, 101,
	197, 101, 84, 121, 41, 19, -7, 19, 161, 37,
	50, 201, 101, 101, -16, 200, 200, 185, 196, 196,
	3, -1000, 19, -1000, 40, -1000, -1000, 132, 19, 73,
	115, 109, -1000, -1000, -1000, -1000, 19, 193, 36, 244,
	244, 34, 244, -1000, 199, 19, 192, -16, -16, 101,
	-1000, 101, -33, 146, -41, -1000, -1000, -1000, 244, 101,
	-1000, 120, 197, 62, 101, 197, 16, 25, -1000, 160,
	159, 158, -1000, 43, 12, -11, -16, -16, -1000, 101,
	-1000, -1000, 178, 244, 101, -1000, 177, 114, -1000, -1000,
	19, 19, 244, 244, 244, 19, 190, 244, 244, 1,
	244, -1000, 171, 244, 59, 157, 156, -1000, -1000, -1000,
	10, 244, 151, 149, 196, -1000, 244, -1000, 170, 244,
	244, 189, -1000, 244, 244, -1000, -1000, 244, -1000, -1000,
	244, -1000, -1000, -1000, -1000,
}

var gritsPgo = [...]uint8{
	0, 117, 242, 241, 239, 238, 237, 0, 27, 9,
	5, 236, 8, 4, 13, 6, 235, 2, 1, 3,
	230, 12, 228, 227,
}

var gritsR1 = [...]int8{
	0, 22, 23, 23, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 2, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 16, 16, 16, 10, 10,
	11, 11, 11, 12, 12, 12, 13, 13, 14, 14,
	9, 9, 8, 8, 8, 8, 21, 5, 3, 3,
	3, 3, 4, 17, 17, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 18, 18, 15, 20, 20, 6,
}

var gritsR2 = [...]int8{
	0, 1, 1, 1, 1, 2, 1, 2, 1, 2,
	1, 2, 1, 2, 6, 8, 7, 10, 6, 5,
	8, 10, 8, 10, 4, 2, 3, 10, 8, 4,
	5, 6, 4, 3, 4, 0, 6, 8, 1, 3,
	0, 1, 3, 0, 1, 3, 0, 2, 1, 3,
	1, 3, 1, 2, 1, 2, 1, 2, 7, 9,
	8, 10, 4, 1, 2, 1, 1, 4, 4, 3,
	3, 3, 4, 4, 3, 5, 1, 1, 1, 4,
}

var gritsChk = [...]int16{
	-1000, -22, -23, -7, -1, 21, 18, -8, 23, 4,
	24, 43, 25, 26, 32, 14, 45, -2, -3, -4,
	-5, -6, 44, -20, 42, 38, 37, 55, 56, 46,
	47, -8, 4, -8, 10, 59, 5, -8, 12, 14,
	-8, -8, -8, -8, -8, -7, 4, -1, -1, -1,
	-1, -1, 44, 4, 16, 4, 4, -14, -9, 4,
	4, 18, 13, 4, -21, 4, 58, 27, 14, -17,
	-19, -15, 4, 50, 46, 49, 14, -11, -8, -8,
	11, 18, 11, 15, 11, -10, -8, 14, 16, 9,
	13, 12, 14, -8, -8, 18, 5, 18, -8, -16,
	4, 59, 48, 53, -19, 7, 8, -15, 51, 51,
	-19, 15, 13, -7, -8, -7, -7, 17, 13, -12,
	-9, 4, -17, -14, -17, 15, 13, 19, -8, 35,
	57, -10, 11, 15, 20, 18, -21, -19, -19, -15,
	4, -15, -18, 4, -18, 15, -10, 19, 9, 12,
	-10, 15, 13, -13, 12, 13, -8, 5, 19, -7,
	-7, 19, -7, 4, -8, 5, -19, -19, 52, 12,
	52, -7, -17, 9, 12, -14, 17, -17, -12, 19,
	22, 33, 11, 11, 11, 18, 19, 35, 57, -19,
	9, -7, -17, 9, -13, -8, -8, -7, -7, -7,
	-8, 6, -7, -7, 13, -7, 9, -7, 17, 11,
	11, 19, -7, 11, 11, -18, -7, 9, -7, -7,
	6, -7, -7, -7, -7,
}

var gritsDef = [...]int8{
	0, -2, 1, 2, 3, 0, 0, 0, 0, 54,
	0, 0, 0, 0, 0, 0, 0, 4, 6, 8,
	10, 12, 52, 0, 0, 0, 0, 0, 0, 77,
	78, 0, 54, 0, 0, 0, 0, 0, 0, 40,
	25, 0, 0, 0, 0, 0, 0, 5, 7, 9,
	11, 13, 53, 55, 0, 0, 0, 57, 48, 50,
	0, 0, 0, 0, 0, 56, 0, 0, 35, 0,
	63, 0, -2, 66, 0, 0, 0, 0, 41, 26,
	0, 0, 0, 33, 0, 0, 38, 43, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 64, 0, 0, 0, 0, 0,
	0, 24, 0, 29, 0, 32, 34, 0, 0, 0,
	44, 46, 62, 49, 51, 79, 0, 0, 0, 0,
	0, 0, 0, 19, 0, 0, 0, 69, 70, 0,
	76, 0, 0, 0, 0, 71, 42, 30, 0, 0,
	39, 0, 0, 0, 0, 43, 0, 0, 18, 0,
	0, 0, 31, 0, 0, 0, 72, 73, 67, 0,
	68, 14, 0, 0, 0, 45, 0, 46, 47, 16,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 74,
	0, 58, 0, 0, 0, 0, 0, 20, 22, 28,
	0, 0, 0, 0, 0, 15, 0, 60, 0, 0,
	0, 0, 36, 0, 0, 75, 59, 0, 17, 27,
	0, 21, 23, 61, 37,
}

var gritsTok1 = [...]int8{
	1,
}

var gritsTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59,
}

var gritsTok3 = [...]int8{
	0,
}

var gritsErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	gritsDebug        = 0
	gritsErrorVerbose = false
)

type gritsLexer interface {
	Lex(lval *gritsSymType) int
	Error(s string)
}

type gritsParser interface {
	Parse(gritsLexer) int
	Lookahead() int
}

type gritsParserImpl struct {
	lval  gritsSymType
	stack [gritsInitialStackSize]gritsSymType
	char  int
}

func (p *gritsParserImpl) Lookahead() int {
	return p.char
}

func gritsNewParser() gritsParser {
	return &gritsParserImpl{}
}

const gritsFlag = -1000

func gritsTokname(c int) string {
	if c >= 1 && c-1 < len(gritsToknames) {
		if gritsToknames[c-1] != "" {
			return gritsToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func gritsStatname(s int) string {
	if s >= 0 && s < len(gritsStatenames) {
		if gritsStatenames[s] != "" {
			return gritsStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func gritsErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !gritsErrorVerbose {
		return "syntax error"
	}

	for _, e := range gritsErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + gritsTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(gritsPact[state])
	for tok := TOKSTART; tok-1 < len(gritsToknames); tok++ {
		if n := base + tok; n >= 0 && n < gritsLast && int(gritsChk[int(gritsAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if gritsDef[state] == -2 {
		i := 0
		for gritsExca[i] != -1 || int(gritsExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; gritsExca[i] >= 0; i += 2 {
			tok := int(gritsExca[i])
			if tok < TOKSTART || gritsExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if gritsExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += gritsTokname(tok)
	}
	return res
}

func gritslex1(lex gritsLexer, lval *gritsSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(gritsTok1[0])
		goto out
	}
	if char < len(gritsTok1) {
		token = int(gritsTok1[char])
		goto out
	}
	if char >= gritsPrivate {
		if char < gritsPrivate+len(gritsTok2) {
			token = int(gritsTok2[char-gritsPrivate])
			goto out
		}
	}
	for i := 0; i < len(gritsTok3); i += 2 {
		token = int(gritsTok3[i+0])
		if token == char {
			token = int(gritsTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(gritsTok2[1]) /* unknown char */
	}
	if gritsDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", gritsTokname(token), uint(char))
	}
	return char, token
}

func gritsParse(gritslex gritsLexer) int {
	return gritsNewParser().Parse(gritslex)
}

func (gritsrcvr *gritsParserImpl) Parse(gritslex gritsLexer) int {
	var gritsn int
	var gritsVAL gritsSymType
	var gritsDollar []gritsSymType
	_ = gritsDollar // silence set and not used
	gritsS := gritsrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	gritsstate := 0
	gritsrcvr.char = -1
	gritstoken := -1 // gritsrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		gritsstate = -1
		gritsrcvr.char = -1
		gritstoken = -1
	}()
	gritsp := -1
	goto gritsstack

ret0:
	return 0

ret1:
	return 1

gritsstack:
	/* put a state and value onto the stack */
	if gritsDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", gritsTokname(gritstoken), gritsStatname(gritsstate))
	}

	gritsp++
	if gritsp >= len(gritsS) {
		nyys := make([]gritsSymType, len(gritsS)*2)
		copy(nyys, gritsS)
		gritsS = nyys
	}
	gritsS[gritsp] = gritsVAL
	gritsS[gritsp].yys = gritsstate

gritsnewstate:
	gritsn = int(gritsPact[gritsstate])
	if gritsn <= gritsFlag {
		goto gritsdefault /* simple state */
	}
	if gritsrcvr.char < 0 {
		gritsrcvr.char, gritstoken = gritslex1(gritslex, &gritsrcvr.lval)
	}
	gritsn += gritstoken
	if gritsn < 0 || gritsn >= gritsLast {
		goto gritsdefault
	}
	gritsn = int(gritsAct[gritsn])
	if int(gritsChk[gritsn]) == gritstoken { /* valid shift */
		gritsrcvr.char = -1
		gritstoken = -1
		gritsVAL = gritsrcvr.lval
		gritsstate = gritsn
		if Errflag > 0 {
			Errflag--
		}
		goto gritsstack
	}

gritsdefault:
	/* default state action */
	gritsn = int(gritsDef[gritsstate])
	if gritsn == -2 {
		if gritsrcvr.char < 0 {
			gritsrcvr.char, gritstoken = gritslex1(gritslex, &gritsrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if gritsExca[xi+0] == -1 && int(gritsExca[xi+1]) == gritsstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			gritsn = int(gritsExca[xi+0])
			if gritsn < 0 || gritsn == gritstoken {
				break
			}
		}
		gritsn = int(gritsExca[xi+1])
		if gritsn < 0 {
			goto ret0
		}
	}
	if gritsn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			gritslex.Error(gritsErrorMessage(gritsstate, gritstoken))
			Nerrs++
			if gritsDebug >= 1 {
				__yyfmt__.Printf("%s", gritsStatname(gritsstate))
				__yyfmt__.Printf(" saw %s\n", gritsTokname(gritstoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for gritsp >= 0 {
				gritsn = int(gritsPact[gritsS[gritsp].yys]) + gritsErrCode
				if gritsn >= 0 && gritsn < gritsLast {
					gritsstate = int(gritsAct[gritsn]) /* simulate a shift of "error" */
					if int(gritsChk[gritsstate]) == gritsErrCode {
						goto gritsstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if gritsDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", gritsS[gritsp].yys)
				}
				gritsp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if gritsDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", gritsTokname(gritstoken))
			}
			if gritstoken == gritsEofCode {
				goto ret1
			}
			gritsrcvr.char = -1
			gritstoken = -1
			goto gritsnewstate /* try again in the same state */
		}
	}

	/* reduction by production gritsn */
	if gritsDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", gritsn, gritsStatname(gritsstate))
	}

	gritsnt := gritsn
	gritspt := gritsp
	_ = gritspt // guard against "declared and not used"

	gritsp -= int(gritsR2[gritsn])
	// gritsp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if gritsp+1 >= len(gritsS) {
		nyys := make([]gritsSymType, len(gritsS)*2)
		copy(nyys, gritsS)
		gritsS = nyys
	}
	gritsVAL = gritsS[gritsp+1]

	/* consult goto table to find next state */
	gritsn = int(gritsR1[gritsn])
	gritsg := int(gritsPgo[gritsn])
	gritsj := gritsg + gritsS[gritsp].yys + 1

	if gritsj >= gritsLast {
		gritsstate = int(gritsAct[gritsg])
	} else {
		gritsstate = int(gritsAct[gritsj])
		if int(gritsChk[gritsstate]) != -gritsn {
			gritsstate = int(gritsAct[gritsg])
		}
	}
	// dummy call; replaced with literal code
	switch gritsnt {

	case 1:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:61
		{
		}
	case 2:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:67
		{
			gritslex.(*lexer).processesOrFunctionsRes = append(gritslex.(*lexer).processesOrFunctionsRes, unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: gritsDollar[1].form, Providers: []process.Name{{Ident: "root", IsSelf: false}}}, position: gritsVAL.currPosition})
		}
	case 3:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:71
		{
			gritslex.(*lexer).processesOrFunctionsRes = gritsDollar[1].statements
		}
	case 4:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:77
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 5:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:78
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 6:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:79
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 7:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:80
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 8:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:81
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 9:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:82
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 10:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:83
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 11:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:84
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 12:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:85
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 13:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:86
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 14:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:92
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: gritsDollar[6].form, Providers: gritsDollar[3].names}, position: gritsVAL.currPosition}
		}
	case 15:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:94
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: gritsDollar[8].form, Type: gritsDollar[6].sessionType, Providers: gritsDollar[3].names}, position: gritsVAL.currPosition}
		}
	case 16:
		gritsDollar = gritsS[gritspt-7 : gritspt+1]
//line parser/parser.y:100
		{
			gritsVAL.form = process.NewSend(gritsDollar[2].name, gritsDollar[4].name, gritsDollar[6].name)
		}
	case 17:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:104
		{
			gritsVAL.form = process.NewReceive(gritsDollar[2].name, gritsDollar[4].name, gritsDollar[8].name, gritsDollar[10].form)
		}
	case 18:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:106
		{
			gritsVAL.form = process.NewSelect(gritsDollar[1].name, process.Label{L: gritsDollar[3].strval}, gritsDollar[5].name)
		}
	case 19:
		gritsDollar = gritsS[gritspt-5 : gritspt+1]
//line parser/parser.y:108
		{
			gritsVAL.form = process.NewCase(gritsDollar[2].name, gritsDollar[4].branches)
		}
	case 20:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:110
		{
			gritsVAL.form = process.NewNew(gritsDollar[1].name, gritsDollar[6].form, gritsDollar[8].form, gritsDollar[3].faultTolerancePromise)
		}
	case 21:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:112
		{
			gritsVAL.form = process.NewNew(process.Name{Ident: gritsDollar[1].strval, Type: gritsDollar[3].sessionType, IsSelf: false}, gritsDollar[8].form, gritsDollar[10].form, gritsDollar[5].faultTolerancePromise)
		}
	case 22:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:114
		{
			gritsVAL.form = process.NewSpawn(gritsDollar[1].name, gritsDollar[6].form, gritsDollar[8].form, gritsDollar[3].faultTolerancePromise)
		}
	case 23:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:116
		{
			gritsVAL.form = process.NewSpawn(process.Name{Ident: gritsDollar[1].strval, Type: gritsDollar[3].sessionType, IsSelf: false}, gritsDollar[8].form, gritsDollar[10].form, gritsDollar[5].faultTolerancePromise)
		}
	case 24:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:118
		{
			gritsVAL.form = process.NewCall(gritsDollar[1].strval, gritsDollar[3].names)
		}
	case 25:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:120
		{
			gritsVAL.form = process.NewClose(gritsDollar[2].name)
		}
	case 26:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:122
		{
			gritsVAL.form = process.NewForward(gritsDollar[2].name, gritsDollar[3].name)
		}
	case 27:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:124
		{
			gritsVAL.form = process.NewSplit(gritsDollar[2].name, gritsDollar[4].name, gritsDollar[8].name, gritsDollar[10].form)
		}
	case 28:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:126
		{
			gritsVAL.form = process.NewSync(gritsDollar[1].name, gritsDollar[5].names, gritsDollar[8].form)
		}
	case 29:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:128
		{
			gritsVAL.form = process.NewWait(gritsDollar[2].name, gritsDollar[4].form)
		}
	case 30:
		gritsDollar = gritsS[gritspt-5 : gritspt+1]
//line parser/parser.y:130
		{
			gritsVAL.form = process.NewCast(gritsDollar[2].name, gritsDollar[4].name)
		}
	case 31:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:132
		{
			gritsVAL.form = process.NewShift(gritsDollar[1].name, gritsDollar[4].name, gritsDollar[6].form)
		}
	case 32:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:134
		{
			gritsVAL.form = process.NewDrop(gritsDollar[2].name, gritsDollar[4].form)
		}
	case 33:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:136
		{
			gritsVAL.form = gritsDollar[2].form
		}
	case 34:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:138
		{
			gritsVAL.form = process.NewPrint(process.Label{L: gritsDollar[2].strval}, gritsDollar[4].form)
		}
	case 35:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:142
		{
			gritsVAL.branches = nil
		}
	case 36:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:143
		{
			gritsVAL.branches = []*process.BranchForm{process.NewBranch(process.Label{L: gritsDollar[1].strval}, gritsDollar[3].name, gritsDollar[6].form)}
		}
	case 37:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:144
		{
			gritsVAL.branches = append(gritsDollar[1].branches, process.NewBranch(process.Label{L: gritsDollar[3].strval}, gritsDollar[5].name, gritsDollar[8].form))
		}
	case 38:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:146
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 39:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:147
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 40:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:149
		{
			gritsVAL.names = nil
		}
	case 41:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:150
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 42:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:151
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 43:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:154
		{
			gritsVAL.names = nil
		}
	case 44:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:155
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 45:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:156
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 46:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:159
		{
			gritsVAL.names = nil
		}
	case 47:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:160
		{
			gritsVAL.names = gritsDollar[2].names
		}
	case 48:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:164
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 49:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:165
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 50:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:170
		{
			gritsVAL.name = process.Name{Ident: gritsDollar[1].strval, IsSelf: false}
		}
	case 51:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:172
		{
			gritsVAL.name = process.Name{Ident: gritsDollar[1].strval, Type: gritsDollar[3].sessionType, IsSelf: false}
		}
	case 52:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:174
		{
			gritsVAL.name = process.Name{IsSelf: true}
		}
	case 53:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:176
		{
			pol := gritsDollar[1].polarity
			gritsVAL.name = process.Name{IsSelf: true, ExplicitPolarity: &pol}
		}
	case 54:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:178
		{
			gritsVAL.name = process.Name{Ident: gritsDollar[1].strval, IsSelf: false}
		}
	case 55:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:180
		{
			pol := gritsDollar[1].polarity
			gritsVAL.name = process.Name{Ident: gritsDollar[2].strval, IsSelf: false, ExplicitPolarity: &pol}
		}
	case 56:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:183
		{
			ftPromise, err := strconv.ParseUint(gritsDollar[1].strval, 10, 64)

			if err != nil {
				gritslex.Error("fault tolerance promise must be a non-negative integer")
			}

			gritsVAL.faultTolerancePromise = ftPromise
		}
	case 57:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:193
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: ASSUMING_DEF, assumedFreeNameTypes: gritsDollar[2].names, position: gritsVAL.currPosition}
		}
	case 58:
		gritsDollar = gritsS[gritspt-7 : gritspt+1]
//line parser/parser.y:198
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{FunctionName: gritsDollar[2].strval, Parameters: gritsDollar[4].names, Body: gritsDollar[7].form, UsesExplicitProvider: false}, position: gritsVAL.currPosition}
		}
	case 59:
		gritsDollar = gritsS[gritspt-9 : gritspt+1]
//line parser/parser.y:200
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{FunctionName: gritsDollar[2].strval, Parameters: gritsDollar[4].names, Body: gritsDollar[9].form, Type: gritsDollar[7].sessionType, UsesExplicitProvider: false}, position: gritsVAL.currPosition}
		}
	case 60:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:203
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{
				FunctionName:         gritsDollar[2].strval,
				Parameters:           gritsDollar[5].names,
				Body:                 gritsDollar[8].form,
				UsesExplicitProvider: true,
				ExplicitProvider:     process.Name{Ident: gritsDollar[4].strval, IsSelf: true},
				// Type: $6,
			}, position: gritsVAL.currPosition}
		}
	case 61:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:214
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{
				FunctionName:         gritsDollar[2].strval,
				Parameters:           gritsDollar[7].names,
				Body:                 gritsDollar[10].form,
				UsesExplicitProvider: true,
				ExplicitProvider:     process.Name{Ident: gritsDollar[4].strval, IsSelf: true},
				Type:                 gritsDollar[6].sessionType}, position: gritsVAL.currPosition}
		}
	case 62:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:224
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{
				kind:         TYPE_DEF,
				session_type: types.SessionTypeDefinition{Name: gritsDollar[2].strval, SessionType: gritsDollar[4].sessionType},
				position:     gritsVAL.currPosition}
		}
	case 63:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:231
		{
			gritsVAL.sessionType = types.ConvertSessionTypeInitialToSessionType(gritsDollar[1].sessionTypeInitial)
		}
	case 64:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:233
		{
			mode := types.StringToMode(gritsDollar[1].strval)
			gritsVAL.sessionType = types.ConvertSessionTypeInitialToSessionType(types.NewExplicitModeTypeInitial(mode, gritsDollar[2].sessionTypeInitial))
		}
	case 65:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:239
		{
			gritsVAL.sessionTypeInitial = types.NewLabelTypeInitial(gritsDollar[1].strval)
		}
	case 66:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:241
		{
			gritsVAL.sessionTypeInitial = types.NewUnitTypeInitial()
		}
	case 67:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:243
		{
			gritsVAL.sessionTypeInitial = types.NewSelectLabelTypeInitial(gritsDollar[3].sessionTypeAltInitial)
		}
	case 68:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:245
		{
			gritsVAL.sessionTypeInitial = types.NewBranchCaseTypeInitial(gritsDollar[3].sessionTypeAltInitial)
		}
	case 69:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:247
		{
			gritsVAL.sessionTypeInitial = types.NewSendTypeInitial(gritsDollar[1].sessionTypeInitial, gritsDollar[3].sessionTypeInitial)
		}
	case 70:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:249
		{
			gritsVAL.sessionTypeInitial = types.NewReceiveTypeInitial(gritsDollar[1].sessionTypeInitial, gritsDollar[3].sessionTypeInitial)
		}
	case 71:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:251
		{
			gritsVAL.sessionTypeInitial = gritsDollar[2].sessionTypeInitial
		}
	case 72:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:253
		{
			modeFrom := types.StringToMode(gritsDollar[1].strval)
			modeTo := types.StringToMode(gritsDollar[3].strval)
			gritsVAL.sessionTypeInitial = types.NewUpTypeInitial(modeFrom, modeTo, gritsDollar[4].sessionTypeInitial)
		}
	case 73:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:257
		{
			modeFrom := types.StringToMode(gritsDollar[1].strval)
			modeTo := types.StringToMode(gritsDollar[3].strval)
			gritsVAL.sessionTypeInitial = types.NewDownTypeInitial(modeFrom, modeTo, gritsDollar[4].sessionTypeInitial)
		}
	case 74:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:263
		{
			gritsVAL.sessionTypeAltInitial = []types.OptionInitial{*types.NewOptionInitial(gritsDollar[1].strval, gritsDollar[3].sessionTypeInitial)}
		}
	case 75:
		gritsDollar = gritsS[gritspt-5 : gritspt+1]
//line parser/parser.y:265
		{
			gritsVAL.sessionTypeAltInitial = append([]types.OptionInitial{*types.NewOptionInitial(gritsDollar[1].strval, gritsDollar[3].sessionTypeInitial)}, gritsDollar[5].sessionTypeAltInitial...)
		}
	case 76:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:267
		{
			gritsVAL.strval = gritsDollar[1].strval
		}
	case 77:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:269
		{
			gritsVAL.polarity = types.POSITIVE
		}
	case 78:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:270
		{
			gritsVAL.polarity = types.NEGATIVE
		}
	case 79:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:274
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{
				kind:     EXEC_DEF,
				proc:     incompleteProcess{Body: process.NewCall(gritsDollar[2].strval, []process.Name{})},
				position: gritsVAL.currPosition}
		}
	}
	goto gritsstack /* stack new state and value */
}
