// Code generated by goyacc -p grits -o parser/parser.y.go parser/parser.y. DO NOT EDIT.

// Run this after each change:
// goyacc -p grits -o parser/parser.y.go parser/parser.y
//
//line parser/parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser/parser.y:4

import (
	"grits/position"
	"grits/process"
	"grits/types"
	"io"
)

//line parser/parser.y:15
type gritsSymType struct {
	yys                   int
	strval                string
	currPosition          position.Position
	common_type           unexpandedProcessOrFunction
	statements            []unexpandedProcessOrFunction
	name                  process.Name
	names                 []process.Name
	form                  process.Form
	branches              []*process.BranchForm
	sessionType           types.SessionType
	sessionTypeInitial    types.SessionTypeInitial
	sessionTypeAltInitial []types.OptionInitial
	polarity              types.Polarity
}

const LABEL = 57346
const LEFT_ARROW = 57347
const RIGHT_ARROW = 57348
const UP_ARROW = 57349
const DOWN_ARROW = 57350
const EQUALS = 57351
const DOT = 57352
const SEQUENCE = 57353
const COLON = 57354
const COMMA = 57355
const LPAREN = 57356
const RPAREN = 57357
const LSBRACK = 57358
const RSBRACK = 57359
const LANGLE = 57360
const RANGLE = 57361
const PIPE = 57362
const SEND = 57363
const RECEIVE = 57364
const CASE = 57365
const CLOSE = 57366
const WAIT = 57367
const CAST = 57368
const SHIFT = 57369
const ACCEPT = 57370
const ACQUIRE = 57371
const DETACH = 57372
const RELEASE = 57373
const DROP = 57374
const SPLIT = 57375
const PUSH = 57376
const NEW = 57377
const SNEW = 57378
const TYPE = 57379
const LET = 57380
const IN = 57381
const END = 57382
const SPRC = 57383
const PRC = 57384
const FORWARD = 57385
const SELF = 57386
const PRINT = 57387
const PLUS = 57388
const MINUS = 57389
const TIMES = 57390
const AMPERSAND = 57391
const UNIT = 57392
const LCBRACK = 57393
const RCBRACK = 57394
const LOLLI = 57395
const PERCENTAGE = 57396
const ASSUMING = 57397
const EXEC = 57398
const SPAWN = 57399

var gritsToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LABEL",
	"LEFT_ARROW",
	"RIGHT_ARROW",
	"UP_ARROW",
	"DOWN_ARROW",
	"EQUALS",
	"DOT",
	"SEQUENCE",
	"COLON",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"LSBRACK",
	"RSBRACK",
	"LANGLE",
	"RANGLE",
	"PIPE",
	"SEND",
	"RECEIVE",
	"CASE",
	"CLOSE",
	"WAIT",
	"CAST",
	"SHIFT",
	"ACCEPT",
	"ACQUIRE",
	"DETACH",
	"RELEASE",
	"DROP",
	"SPLIT",
	"PUSH",
	"NEW",
	"SNEW",
	"TYPE",
	"LET",
	"IN",
	"END",
	"SPRC",
	"PRC",
	"FORWARD",
	"SELF",
	"PRINT",
	"PLUS",
	"MINUS",
	"TIMES",
	"AMPERSAND",
	"UNIT",
	"LCBRACK",
	"RCBRACK",
	"LOLLI",
	"PERCENTAGE",
	"ASSUMING",
	"EXEC",
	"SPAWN",
}

var gritsStatenames = [...]string{}

const gritsEofCode = 1
const gritsErrCode = 2
const gritsInitialStackSize = 16

//line parser/parser.y:265

// Parse is the entry point to the parser.
func Parse(r io.Reader) (allEnvironment, error) {
	l := newLexer(r)
	gritsParse(l)
	allEnvironment := allEnvironment{}
	select {
	case err := <-l.Errors:
		return allEnvironment, err
	default:
		// allEnvironment := l
		allEnvironment.procsAndFuns = l.processesOrFunctionsRes
		return allEnvironment, nil
	}
}

//line yacctab:1
var gritsExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 70,
	4, 74,
	7, 74,
	8, 74,
	14, 74,
	46, 74,
	49, 74,
	50, 74,
	-2, 63,
}

const gritsPrivate = 57344

const gritsLast = 258

var gritsAct = [...]uint8{
	3, 140, 151, 105, 168, 117, 83, 166, 26, 25,
	57, 107, 67, 24, 68, 9, 44, 56, 100, 106,
	65, 52, 203, 101, 181, 15, 27, 28, 63, 6,
	133, 196, 5, 7, 8, 10, 12, 13, 178, 31,
	33, 69, 36, 14, 39, 40, 41, 42, 43, 179,
	64, 177, 134, 156, 11, 22, 16, 29, 30, 70,
	145, 51, 103, 104, 94, 95, 100, 125, 130, 74,
	180, 101, 76, 131, 77, 132, 93, 79, 32, 111,
	70, 113, 60, 114, 102, 200, 143, 84, 53, 108,
	74, 69, 174, 69, 91, 92, 118, 115, 149, 96,
	120, 72, 122, 123, 73, 71, 121, 137, 139, 142,
	85, 90, 86, 112, 109, 135, 136, 144, 22, 100,
	29, 30, 72, 148, 101, 73, 71, 126, 157, 158,
	159, 81, 152, 153, 162, 163, 37, 66, 38, 153,
	171, 150, 146, 172, 84, 147, 167, 169, 124, 116,
	84, 69, 164, 110, 165, 88, 69, 61, 154, 176,
	170, 89, 202, 201, 118, 175, 161, 183, 173, 182,
	129, 128, 186, 127, 82, 80, 69, 78, 189, 207,
	198, 188, 184, 194, 195, 187, 197, 35, 185, 199,
	103, 104, 34, 87, 204, 210, 193, 155, 205, 206,
	99, 141, 208, 209, 58, 9, 160, 138, 211, 119,
	4, 212, 190, 191, 192, 15, 98, 62, 59, 6,
	55, 54, 5, 45, 8, 10, 12, 13, 46, 47,
	48, 49, 50, 14, 2, 1, 23, 97, 26, 25,
	75, 21, 20, 24, 11, 22, 16, 29, 30, 19,
	18, 17, 0, 0, 0, 0, 27, 28,
}

var gritsPact = [...]int16{
	201, -1000, -1000, -1000, -1000, 74, 74, 182, 74, 124,
	74, 74, 74, 74, 74, 11, 219, -29, -29, -29,
	-29, -29, -1000, 17, 72, 217, 216, 200, 214, -1000,
	-1000, 64, -1000, 144, 213, -7, 123, 76, 74, -1000,
	74, 166, 59, 164, 116, 163, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 74, 96, 184, -1000, 142, 149, 97,
	74, 74, 58, 11, 11, 74, 212, 195, -30, 55,
	-1000, -1000, -32, -40, 76, 99, 140, -1000, 11, 74,
	11, -1000, 11, 80, 136, 200, 205, 76, 200, 76,
	88, 135, 48, 74, 162, 160, 159, 53, 57, -5,
	76, 76, -30, 203, 203, 183, 197, 197, 71, -1000,
	74, -1000, 41, -1000, -1000, 133, 74, 83, 128, 120,
	-1000, -1000, -1000, -1000, 74, 192, 34, 11, 11, 11,
	-1000, 202, 74, 11, 11, -30, -30, 76, -1000, 76,
	-45, 134, -48, -1000, -1000, -1000, 11, 76, -1000, 131,
	200, 75, 76, 200, 32, 16, -1000, -1000, -1000, -1000,
	52, 5, 158, 156, -30, -30, -1000, 76, -1000, -1000,
	179, 11, 76, -1000, 172, 126, -1000, -1000, 74, 74,
	74, 190, 11, 11, 18, 11, -1000, 171, 11, 68,
	152, 151, 3, 11, -1000, -1000, 197, -1000, 11, -1000,
	170, 11, 11, 189, -1000, -1000, -1000, 11, -1000, -1000,
	11, -1000, -1000,
}

var gritsPgo = [...]uint8{
	0, 210, 251, 250, 249, 242, 241, 0, 33, 10,
	6, 240, 5, 2, 17, 3, 237, 12, 1, 14,
	236, 235, 234,
}

var gritsR1 = [...]int8{
	0, 21, 22, 22, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 2, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 16, 16, 16, 10, 10, 11,
	11, 11, 12, 12, 12, 13, 13, 14, 14, 9,
	9, 8, 8, 8, 8, 5, 3, 3, 3, 3,
	4, 17, 17, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 18, 18, 15, 20, 20, 6,
}

var gritsR2 = [...]int8{
	0, 1, 1, 1, 1, 2, 1, 2, 1, 2,
	1, 2, 1, 2, 6, 8, 7, 10, 6, 5,
	6, 8, 6, 8, 4, 2, 3, 10, 4, 5,
	6, 4, 3, 4, 0, 6, 8, 1, 3, 0,
	1, 3, 0, 1, 3, 0, 2, 1, 3, 1,
	3, 1, 2, 1, 2, 2, 7, 9, 8, 10,
	4, 1, 2, 1, 1, 4, 4, 3, 3, 3,
	4, 4, 3, 5, 1, 1, 1, 4,
}

var gritsChk = [...]int16{
	-1000, -21, -22, -7, -1, 21, 18, -8, 23, 4,
	24, 43, 25, 26, 32, 14, 45, -2, -3, -4,
	-5, -6, 44, -20, 42, 38, 37, 55, 56, 46,
	47, -8, 4, -8, 10, 5, -8, 12, 14, -8,
	-8, -8, -8, -8, -7, 4, -1, -1, -1, -1,
	-1, 44, 4, 16, 4, 4, -14, -9, 4, 4,
	18, 13, 4, 35, 57, 27, 14, -17, -19, -15,
	4, 50, 46, 49, 14, -11, -8, -8, 11, 18,
	11, 15, 11, -10, -8, 14, 16, 9, 13, 12,
	14, -8, -8, 18, -7, -7, -8, -16, 4, 5,
	48, 53, -19, 7, 8, -15, 51, 51, -19, 15,
	13, -7, -8, -7, -7, 17, 13, -12, -9, 4,
	-17, -14, -17, 15, 13, 19, -8, 11, 11, 11,
	15, 20, 18, 35, 57, -19, -19, -15, 4, -15,
	-18, 4, -18, 15, -10, 19, 9, 12, -10, 15,
	13, -13, 12, 13, -8, 5, 19, -7, -7, -7,
	4, -8, -7, -7, -19, -19, 52, 12, 52, -7,
	-17, 9, 12, -14, 17, -17, -12, 19, 22, 33,
	18, 19, 11, 11, -19, 9, -7, -17, 9, -13,
	-8, -8, -8, 6, -7, -7, 13, -7, 9, -7,
	17, 11, 11, 19, -7, -18, -7, 9, -7, -7,
	6, -7, -7,
}

var gritsDef = [...]int8{
	0, -2, 1, 2, 3, 0, 0, 0, 0, 53,
	0, 0, 0, 0, 0, 0, 0, 4, 6, 8,
	10, 12, 51, 0, 0, 0, 0, 0, 0, 75,
	76, 0, 53, 0, 0, 0, 0, 0, 39, 25,
	0, 0, 0, 0, 0, 0, 5, 7, 9, 11,
	13, 52, 54, 0, 0, 0, 55, 47, 49, 0,
	0, 0, 0, 0, 0, 0, 34, 0, 61, 0,
	-2, 64, 0, 0, 0, 0, 40, 26, 0, 0,
	0, 32, 0, 0, 37, 42, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 62, 0, 0, 0, 0, 0, 0, 24,
	0, 28, 0, 31, 33, 0, 0, 0, 43, 45,
	60, 48, 50, 77, 0, 0, 0, 0, 0, 0,
	19, 0, 0, 0, 0, 67, 68, 0, 74, 0,
	0, 0, 0, 69, 41, 29, 0, 0, 38, 0,
	0, 0, 0, 42, 0, 0, 18, 20, 22, 30,
	0, 0, 0, 0, 70, 71, 65, 0, 66, 14,
	0, 0, 0, 44, 0, 45, 46, 16, 0, 0,
	0, 0, 0, 0, 72, 0, 56, 0, 0, 0,
	0, 0, 0, 0, 21, 23, 0, 15, 0, 58,
	0, 0, 0, 0, 35, 73, 57, 0, 17, 27,
	0, 59, 36,
}

var gritsTok1 = [...]int8{
	1,
}

var gritsTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57,
}

var gritsTok3 = [...]int8{
	0,
}

var gritsErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	gritsDebug        = 0
	gritsErrorVerbose = false
)

type gritsLexer interface {
	Lex(lval *gritsSymType) int
	Error(s string)
}

type gritsParser interface {
	Parse(gritsLexer) int
	Lookahead() int
}

type gritsParserImpl struct {
	lval  gritsSymType
	stack [gritsInitialStackSize]gritsSymType
	char  int
}

func (p *gritsParserImpl) Lookahead() int {
	return p.char
}

func gritsNewParser() gritsParser {
	return &gritsParserImpl{}
}

const gritsFlag = -1000

func gritsTokname(c int) string {
	if c >= 1 && c-1 < len(gritsToknames) {
		if gritsToknames[c-1] != "" {
			return gritsToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func gritsStatname(s int) string {
	if s >= 0 && s < len(gritsStatenames) {
		if gritsStatenames[s] != "" {
			return gritsStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func gritsErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !gritsErrorVerbose {
		return "syntax error"
	}

	for _, e := range gritsErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + gritsTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(gritsPact[state])
	for tok := TOKSTART; tok-1 < len(gritsToknames); tok++ {
		if n := base + tok; n >= 0 && n < gritsLast && int(gritsChk[int(gritsAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if gritsDef[state] == -2 {
		i := 0
		for gritsExca[i] != -1 || int(gritsExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; gritsExca[i] >= 0; i += 2 {
			tok := int(gritsExca[i])
			if tok < TOKSTART || gritsExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if gritsExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += gritsTokname(tok)
	}
	return res
}

func gritslex1(lex gritsLexer, lval *gritsSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(gritsTok1[0])
		goto out
	}
	if char < len(gritsTok1) {
		token = int(gritsTok1[char])
		goto out
	}
	if char >= gritsPrivate {
		if char < gritsPrivate+len(gritsTok2) {
			token = int(gritsTok2[char-gritsPrivate])
			goto out
		}
	}
	for i := 0; i < len(gritsTok3); i += 2 {
		token = int(gritsTok3[i+0])
		if token == char {
			token = int(gritsTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(gritsTok2[1]) /* unknown char */
	}
	if gritsDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", gritsTokname(token), uint(char))
	}
	return char, token
}

func gritsParse(gritslex gritsLexer) int {
	return gritsNewParser().Parse(gritslex)
}

func (gritsrcvr *gritsParserImpl) Parse(gritslex gritsLexer) int {
	var gritsn int
	var gritsVAL gritsSymType
	var gritsDollar []gritsSymType
	_ = gritsDollar // silence set and not used
	gritsS := gritsrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	gritsstate := 0
	gritsrcvr.char = -1
	gritstoken := -1 // gritsrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		gritsstate = -1
		gritsrcvr.char = -1
		gritstoken = -1
	}()
	gritsp := -1
	goto gritsstack

ret0:
	return 0

ret1:
	return 1

gritsstack:
	/* put a state and value onto the stack */
	if gritsDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", gritsTokname(gritstoken), gritsStatname(gritsstate))
	}

	gritsp++
	if gritsp >= len(gritsS) {
		nyys := make([]gritsSymType, len(gritsS)*2)
		copy(nyys, gritsS)
		gritsS = nyys
	}
	gritsS[gritsp] = gritsVAL
	gritsS[gritsp].yys = gritsstate

gritsnewstate:
	gritsn = int(gritsPact[gritsstate])
	if gritsn <= gritsFlag {
		goto gritsdefault /* simple state */
	}
	if gritsrcvr.char < 0 {
		gritsrcvr.char, gritstoken = gritslex1(gritslex, &gritsrcvr.lval)
	}
	gritsn += gritstoken
	if gritsn < 0 || gritsn >= gritsLast {
		goto gritsdefault
	}
	gritsn = int(gritsAct[gritsn])
	if int(gritsChk[gritsn]) == gritstoken { /* valid shift */
		gritsrcvr.char = -1
		gritstoken = -1
		gritsVAL = gritsrcvr.lval
		gritsstate = gritsn
		if Errflag > 0 {
			Errflag--
		}
		goto gritsstack
	}

gritsdefault:
	/* default state action */
	gritsn = int(gritsDef[gritsstate])
	if gritsn == -2 {
		if gritsrcvr.char < 0 {
			gritsrcvr.char, gritstoken = gritslex1(gritslex, &gritsrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if gritsExca[xi+0] == -1 && int(gritsExca[xi+1]) == gritsstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			gritsn = int(gritsExca[xi+0])
			if gritsn < 0 || gritsn == gritstoken {
				break
			}
		}
		gritsn = int(gritsExca[xi+1])
		if gritsn < 0 {
			goto ret0
		}
	}
	if gritsn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			gritslex.Error(gritsErrorMessage(gritsstate, gritstoken))
			Nerrs++
			if gritsDebug >= 1 {
				__yyfmt__.Printf("%s", gritsStatname(gritsstate))
				__yyfmt__.Printf(" saw %s\n", gritsTokname(gritstoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for gritsp >= 0 {
				gritsn = int(gritsPact[gritsS[gritsp].yys]) + gritsErrCode
				if gritsn >= 0 && gritsn < gritsLast {
					gritsstate = int(gritsAct[gritsn]) /* simulate a shift of "error" */
					if int(gritsChk[gritsstate]) == gritsErrCode {
						goto gritsstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if gritsDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", gritsS[gritsp].yys)
				}
				gritsp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if gritsDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", gritsTokname(gritstoken))
			}
			if gritstoken == gritsEofCode {
				goto ret1
			}
			gritsrcvr.char = -1
			gritstoken = -1
			goto gritsnewstate /* try again in the same state */
		}
	}

	/* reduction by production gritsn */
	if gritsDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", gritsn, gritsStatname(gritsstate))
	}

	gritsnt := gritsn
	gritspt := gritsp
	_ = gritspt // guard against "declared and not used"

	gritsp -= int(gritsR2[gritsn])
	// gritsp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if gritsp+1 >= len(gritsS) {
		nyys := make([]gritsSymType, len(gritsS)*2)
		copy(nyys, gritsS)
		gritsS = nyys
	}
	gritsVAL = gritsS[gritsp+1]

	/* consult goto table to find next state */
	gritsn = int(gritsR1[gritsn])
	gritsg := int(gritsPgo[gritsn])
	gritsj := gritsg + gritsS[gritsp].yys + 1

	if gritsj >= gritsLast {
		gritsstate = int(gritsAct[gritsg])
	} else {
		gritsstate = int(gritsAct[gritsj])
		if int(gritsChk[gritsstate]) != -gritsn {
			gritsstate = int(gritsAct[gritsg])
		}
	}
	// dummy call; replaced with literal code
	switch gritsnt {

	case 1:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:58
		{
		}
	case 2:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:64
		{
			gritslex.(*lexer).processesOrFunctionsRes = append(gritslex.(*lexer).processesOrFunctionsRes, unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: gritsDollar[1].form, Providers: []process.Name{{Ident: "root", IsSelf: false}}}, position: gritsVAL.currPosition})
		}
	case 3:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:68
		{
			gritslex.(*lexer).processesOrFunctionsRes = gritsDollar[1].statements
		}
	case 4:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:74
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 5:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:75
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 6:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:76
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 7:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:77
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 8:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:78
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 9:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:79
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 10:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:80
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 11:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:81
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 12:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:82
		{
			gritsVAL.statements = []unexpandedProcessOrFunction{gritsDollar[1].common_type}
		}
	case 13:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:83
		{
			gritsVAL.statements = append([]unexpandedProcessOrFunction{gritsDollar[1].common_type}, gritsDollar[2].statements...)
		}
	case 14:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:89
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: gritsDollar[6].form, Providers: gritsDollar[3].names}, position: gritsVAL.currPosition}
		}
	case 15:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:91
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: gritsDollar[8].form, Type: gritsDollar[6].sessionType, Providers: gritsDollar[3].names}, position: gritsVAL.currPosition}
		}
	case 16:
		gritsDollar = gritsS[gritspt-7 : gritspt+1]
//line parser/parser.y:97
		{
			gritsVAL.form = process.NewSend(gritsDollar[2].name, gritsDollar[4].name, gritsDollar[6].name)
		}
	case 17:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:101
		{
			gritsVAL.form = process.NewReceive(gritsDollar[2].name, gritsDollar[4].name, gritsDollar[8].name, gritsDollar[10].form)
		}
	case 18:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:103
		{
			gritsVAL.form = process.NewSelect(gritsDollar[1].name, process.Label{L: gritsDollar[3].strval}, gritsDollar[5].name)
		}
	case 19:
		gritsDollar = gritsS[gritspt-5 : gritspt+1]
//line parser/parser.y:105
		{
			gritsVAL.form = process.NewCase(gritsDollar[2].name, gritsDollar[4].branches)
		}
	case 20:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:107
		{
			gritsVAL.form = process.NewNew(gritsDollar[1].name, gritsDollar[4].form, gritsDollar[6].form)
		}
	case 21:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:109
		{
			gritsVAL.form = process.NewNew(process.Name{Ident: gritsDollar[1].strval, Type: gritsDollar[3].sessionType, IsSelf: false}, gritsDollar[6].form, gritsDollar[8].form)
		}
	case 22:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:111
		{
			gritsVAL.form = process.NewSpawn(gritsDollar[1].name, gritsDollar[4].form, gritsDollar[6].form)
		}
	case 23:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:113
		{
			gritsVAL.form = process.NewSpawn(process.Name{Ident: gritsDollar[1].strval, Type: gritsDollar[3].sessionType, IsSelf: false}, gritsDollar[6].form, gritsDollar[8].form)
		}
	case 24:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:115
		{
			gritsVAL.form = process.NewCall(gritsDollar[1].strval, gritsDollar[3].names)
		}
	case 25:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:117
		{
			gritsVAL.form = process.NewClose(gritsDollar[2].name)
		}
	case 26:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:119
		{
			gritsVAL.form = process.NewForward(gritsDollar[2].name, gritsDollar[3].name)
		}
	case 27:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:121
		{
			gritsVAL.form = process.NewSplit(gritsDollar[2].name, gritsDollar[4].name, gritsDollar[8].name, gritsDollar[10].form)
		}
	case 28:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:123
		{
			gritsVAL.form = process.NewWait(gritsDollar[2].name, gritsDollar[4].form)
		}
	case 29:
		gritsDollar = gritsS[gritspt-5 : gritspt+1]
//line parser/parser.y:125
		{
			gritsVAL.form = process.NewCast(gritsDollar[2].name, gritsDollar[4].name)
		}
	case 30:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:127
		{
			gritsVAL.form = process.NewShift(gritsDollar[1].name, gritsDollar[4].name, gritsDollar[6].form)
		}
	case 31:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:129
		{
			gritsVAL.form = process.NewDrop(gritsDollar[2].name, gritsDollar[4].form)
		}
	case 32:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:131
		{
			gritsVAL.form = gritsDollar[2].form
		}
	case 33:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:133
		{
			gritsVAL.form = process.NewPrint(process.Label{L: gritsDollar[2].strval}, gritsDollar[4].form)
		}
	case 34:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:137
		{
			gritsVAL.branches = nil
		}
	case 35:
		gritsDollar = gritsS[gritspt-6 : gritspt+1]
//line parser/parser.y:138
		{
			gritsVAL.branches = []*process.BranchForm{process.NewBranch(process.Label{L: gritsDollar[1].strval}, gritsDollar[3].name, gritsDollar[6].form)}
		}
	case 36:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:139
		{
			gritsVAL.branches = append(gritsDollar[1].branches, process.NewBranch(process.Label{L: gritsDollar[3].strval}, gritsDollar[5].name, gritsDollar[8].form))
		}
	case 37:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:141
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 38:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:142
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 39:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:144
		{
			gritsVAL.names = nil
		}
	case 40:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:145
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 41:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:146
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 42:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:149
		{
			gritsVAL.names = nil
		}
	case 43:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:150
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 44:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:151
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 45:
		gritsDollar = gritsS[gritspt-0 : gritspt+1]
//line parser/parser.y:154
		{
			gritsVAL.names = nil
		}
	case 46:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:155
		{
			gritsVAL.names = gritsDollar[2].names
		}
	case 47:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:159
		{
			gritsVAL.names = []process.Name{gritsDollar[1].name}
		}
	case 48:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:160
		{
			gritsVAL.names = append([]process.Name{gritsDollar[1].name}, gritsDollar[3].names...)
		}
	case 49:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:165
		{
			gritsVAL.name = process.Name{Ident: gritsDollar[1].strval, IsSelf: false}
		}
	case 50:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:167
		{
			gritsVAL.name = process.Name{Ident: gritsDollar[1].strval, Type: gritsDollar[3].sessionType, IsSelf: false}
		}
	case 51:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:169
		{
			gritsVAL.name = process.Name{IsSelf: true}
		}
	case 52:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:171
		{
			pol := gritsDollar[1].polarity
			gritsVAL.name = process.Name{IsSelf: true, ExplicitPolarity: &pol}
		}
	case 53:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:173
		{
			gritsVAL.name = process.Name{Ident: gritsDollar[1].strval, IsSelf: false}
		}
	case 54:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:175
		{
			pol := gritsDollar[1].polarity
			gritsVAL.name = process.Name{Ident: gritsDollar[2].strval, IsSelf: false, ExplicitPolarity: &pol}
		}
	case 55:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:179
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: ASSUMING_DEF, assumedFreeNameTypes: gritsDollar[2].names, position: gritsVAL.currPosition}
		}
	case 56:
		gritsDollar = gritsS[gritspt-7 : gritspt+1]
//line parser/parser.y:184
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{FunctionName: gritsDollar[2].strval, Parameters: gritsDollar[4].names, Body: gritsDollar[7].form, UsesExplicitProvider: false}, position: gritsVAL.currPosition}
		}
	case 57:
		gritsDollar = gritsS[gritspt-9 : gritspt+1]
//line parser/parser.y:186
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{FunctionName: gritsDollar[2].strval, Parameters: gritsDollar[4].names, Body: gritsDollar[9].form, Type: gritsDollar[7].sessionType, UsesExplicitProvider: false}, position: gritsVAL.currPosition}
		}
	case 58:
		gritsDollar = gritsS[gritspt-8 : gritspt+1]
//line parser/parser.y:189
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{
				FunctionName:         gritsDollar[2].strval,
				Parameters:           gritsDollar[5].names,
				Body:                 gritsDollar[8].form,
				UsesExplicitProvider: true,
				ExplicitProvider:     process.Name{Ident: gritsDollar[4].strval, IsSelf: true},
				// Type: $6,
			}, position: gritsVAL.currPosition}
		}
	case 59:
		gritsDollar = gritsS[gritspt-10 : gritspt+1]
//line parser/parser.y:200
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{
				FunctionName:         gritsDollar[2].strval,
				Parameters:           gritsDollar[7].names,
				Body:                 gritsDollar[10].form,
				UsesExplicitProvider: true,
				ExplicitProvider:     process.Name{Ident: gritsDollar[4].strval, IsSelf: true},
				Type:                 gritsDollar[6].sessionType}, position: gritsVAL.currPosition}
		}
	case 60:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:210
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{
				kind:         TYPE_DEF,
				session_type: types.SessionTypeDefinition{Name: gritsDollar[2].strval, SessionType: gritsDollar[4].sessionType},
				position:     gritsVAL.currPosition}
		}
	case 61:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:217
		{
			gritsVAL.sessionType = types.ConvertSessionTypeInitialToSessionType(gritsDollar[1].sessionTypeInitial)
		}
	case 62:
		gritsDollar = gritsS[gritspt-2 : gritspt+1]
//line parser/parser.y:219
		{
			mode := types.StringToMode(gritsDollar[1].strval)
			gritsVAL.sessionType = types.ConvertSessionTypeInitialToSessionType(types.NewExplicitModeTypeInitial(mode, gritsDollar[2].sessionTypeInitial))
		}
	case 63:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:225
		{
			gritsVAL.sessionTypeInitial = types.NewLabelTypeInitial(gritsDollar[1].strval)
		}
	case 64:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:227
		{
			gritsVAL.sessionTypeInitial = types.NewUnitTypeInitial()
		}
	case 65:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:229
		{
			gritsVAL.sessionTypeInitial = types.NewSelectLabelTypeInitial(gritsDollar[3].sessionTypeAltInitial)
		}
	case 66:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:231
		{
			gritsVAL.sessionTypeInitial = types.NewBranchCaseTypeInitial(gritsDollar[3].sessionTypeAltInitial)
		}
	case 67:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:233
		{
			gritsVAL.sessionTypeInitial = types.NewSendTypeInitial(gritsDollar[1].sessionTypeInitial, gritsDollar[3].sessionTypeInitial)
		}
	case 68:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:235
		{
			gritsVAL.sessionTypeInitial = types.NewReceiveTypeInitial(gritsDollar[1].sessionTypeInitial, gritsDollar[3].sessionTypeInitial)
		}
	case 69:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:237
		{
			gritsVAL.sessionTypeInitial = gritsDollar[2].sessionTypeInitial
		}
	case 70:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:239
		{
			modeFrom := types.StringToMode(gritsDollar[1].strval)
			modeTo := types.StringToMode(gritsDollar[3].strval)
			gritsVAL.sessionTypeInitial = types.NewUpTypeInitial(modeFrom, modeTo, gritsDollar[4].sessionTypeInitial)
		}
	case 71:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:243
		{
			modeFrom := types.StringToMode(gritsDollar[1].strval)
			modeTo := types.StringToMode(gritsDollar[3].strval)
			gritsVAL.sessionTypeInitial = types.NewDownTypeInitial(modeFrom, modeTo, gritsDollar[4].sessionTypeInitial)
		}
	case 72:
		gritsDollar = gritsS[gritspt-3 : gritspt+1]
//line parser/parser.y:249
		{
			gritsVAL.sessionTypeAltInitial = []types.OptionInitial{*types.NewOptionInitial(gritsDollar[1].strval, gritsDollar[3].sessionTypeInitial)}
		}
	case 73:
		gritsDollar = gritsS[gritspt-5 : gritspt+1]
//line parser/parser.y:251
		{
			gritsVAL.sessionTypeAltInitial = append([]types.OptionInitial{*types.NewOptionInitial(gritsDollar[1].strval, gritsDollar[3].sessionTypeInitial)}, gritsDollar[5].sessionTypeAltInitial...)
		}
	case 74:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:253
		{
			gritsVAL.strval = gritsDollar[1].strval
		}
	case 75:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:255
		{
			gritsVAL.polarity = types.POSITIVE
		}
	case 76:
		gritsDollar = gritsS[gritspt-1 : gritspt+1]
//line parser/parser.y:256
		{
			gritsVAL.polarity = types.NEGATIVE
		}
	case 77:
		gritsDollar = gritsS[gritspt-4 : gritspt+1]
//line parser/parser.y:260
		{
			gritsVAL.common_type = unexpandedProcessOrFunction{
				kind:     EXEC_DEF,
				proc:     incompleteProcess{Body: process.NewCall(gritsDollar[2].strval, []process.Name{})},
				position: gritsVAL.currPosition}
		}
	}
	goto gritsstack /* stack new state and value */
}
